# Archivo de configuración YAML para configurar y
# ejecutar un contenedor Docker de PostgreSQL

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: jose
      POSTGRES_PASSWORD: josejose
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: